### PR TITLE
Add error for when address is in use

### PR DESCRIPTION
**Pull request by derekdreery**
This is a bit fiddly, since hyper doesn't really report this error. Instead, we have to rely on hyper using the underlying std::net::TcpListener, which produces `io::Error`s. We can then match the error code to EADDR to see if the address is in use. If in the future hyper uses something other than `std::net::TcpListener`, then address in use would be come a standard hyper error, and we then rely on hyper printing out something useful.

### CODE REVIEW

**Comment by derekdreery** [comment]
This is based on the structopt patch. If you reject that one, I can rebase this on master.

**Comment by brson** [comment]
Thanks again @derekdreery !

**Comment by brson** [comment]
Actually @derekdreery, this PR didn't behave the way I expected it to:

I expected that if I run `basic-http-server` twice, the second one will produce an error about binding to the same socket/port, but I am not seeing that behavior. Instead the second instance runs, but receives to connections.

For now I've reverted this change until I understand it. I'm afraid I don't seem to be able to simply re-open this PR though.

**Comment by derekdreery** [comment]
I'm going to have a look at why this didn't work - it seemed to on my machine!

**Pull request merged**
